version: '3.9'
services:
  central_system:
    build: ./centralSystem
    ports:
      - 9000:9000
  charge_point:
    build: ./chargePoint
    depends_on:
      - monitoring_system
  monitoring_system:
    image: mitmproxy/mitmproxy
    volumes:
      - ./monitoringSystem/src:/var/python-scripts
    command: mitmdump -p 9000 --mode reverse:central_system:9000 -s /var/python-scripts/index.py
    expose:
      - 9000
    depends_on:
      - central_system