version: '3.9'
services:
  centralsystem:
    build: ./centralSystem
    depends_on:
      - monitoringsystem
    expose:
      - 9000

  monitoringsystem:
    build:
      ./monitoringSystem
    expose:
      - 9000
    volumes:
      - ./monitoringSystem/src:/app/src:rw

  charge_point_1:
    build: ./chargePoint
    depends_on:
      - monitoringsystem

  charge_point_2:
    build: ./chargePoint
    depends_on:
      - monitoringsystem
  
  monitoring_log:
    build: ./backend
    expose:
      - 3001
      - 3000
    ports:
      - "3001:3000"
  frontend:
    build: ./ocpp-monitoring-ui
    volumes:
      - './ocpp-monitoring-ui:/app'
      - './ocpp-monitoring-ui/node_modules:/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    extends:
      file: service.yml
      service: frontend
    depends_on:
    - monitoring_log

  authentication_system:
    build: ./authenticationSystem
    expose:
      - 3000
    volumes:
      - ./authenticationSystem:/app
    environment:
      - SIGNING_KEY=thismustbethebestkey

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
