version: '3.9'
services:
  centralsystem:
    build: ./centralSystem
    expose:
      - 9000

  monitoringsystem:
    build:
      ./monitoringSystem
    expose:
      - 9000
    volumes:
      - ./monitoringSystem/src:/app/src:rw

  charge_point_1:
    build: ./chargePoint
  
  monitoring_log:
    build: ./backend
    expose:
      - 3001
      - 3000
    ports:
      - "3001:3000"

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
