version: '3.9'
services:
  central_system:
    build: ./centralSystem
    expose:
      - 9000
  monitoring_system:
    build: ./monitoringSystem
    expose:
      - 9000
    depends_on:
      - central_system
  monitoring_log:
    build: ./backend
    expose:
      - 3000
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  
  charge_point_1:
    build: ./chargePoint
    depends_on:
      - monitoring_system

  charge_point_2:
    build: ./chargePoint
    depends_on:
      - monitoring_system
