version: '3'
services:
  central_system:
    build: ./centralSystem
    expose:
      - 9000

  monitoring_system:
    build: ./monitoringSystem
    expose:
      - 9000
    depends_on:
      - central_system

  monitoring_log:
    build: ./backend
    expose:
      - 3001
      - 3000
    ports:
      - "3001:3000"
    depends_on:
      - user_service
    volumes:
      - ./backend:/code
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  frontend:
    build: ./ocpp-monitoring-ui
    command: yarn dev
    volumes:
      - './ocpp-monitoring-ui:/app'
      - './ocpp-monitoring-ui/node_modules:/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    extends:
      file: service.yml
      service: frontend
    depends_on:
    - monitoring_log
  
  charge_point_1:
    build: ./chargePoint
    depends_on:
      - monitoring_system

  charge_point_2:
    build: ./chargePoint
    depends_on:
      - monitoring_system

  user_service:
    build: ./userService
    expose:
      - 3000
    ports:
      - "3002:3000"
    volumes:
      - ./userService:/code
