version: '3.9'
services:
  central_system:
    build: ./centralSystem
    expose:
      - 9000

  monitoring_system:
    build: ./monitoringSystem
    expose:
      - 9000
    depends_on:
      - central_system

  monitoring_log:
    build: ./backend
    expose:
      - 3001
      - 3000
    ports:
      - "3001:3000"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend/test-react/monitoring-ui
    volumes:
      - './frontend/test-react/monitoring-ui:/app'
      - './frontend/test-react/monitoring-ui/node_modules:/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
    - monitoring_log
  
  charge_point_1:
    build: ./chargePoint
    depends_on:
      - monitoring_system

  charge_point_2:
    build: ./chargePoint
    depends_on:
      - monitoring_system
