apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: authentication-system
  name: authentication_system
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: authentication-system
status:
  loadBalancer: {}
