apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: central-system
  name: central_system
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: central-system
status:
  loadBalancer: {}
