apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring-log
  name: monitoring-log
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monitoring-log
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: monitoring-log
    spec:
      containers:
        - image: monitoring-log
          name: monitoring_log
          ports:
            - containerPort: 3000
            - containerPort: 3001
          resources: {}
      restartPolicy: Always
status: {}
