apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring-log
  name: monitoring_log
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3000
    - name: 3001-tcp
      port: 3001
      targetPort: 3001
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: monitoring-log
status:
  loadBalancer: {}
