apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring-system
  name: monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monitoring-system
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: monitoring-system
    spec:
      containers:
        - image: monitoring-system
          name: monitoring_system
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
